### ISSUE TITLE
Dismiss keyboard after changing the note title

### ISSUE THREAD

**Issue by ges1227** [nextcloud/notes-android#1259]
Please use **[GitHub reactions](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/)** 👍 to show that you are affected by the same issue. Please don't comment if you have no relevant information to add!

**Describe the bug**

When viewing a note there is an option to click on the title in the action bar to change the name of the note.
This opens a modal and the keyboard. 
After "saving" or "canceling" the title change, the modal is closed while the keyboard remains open and is not discarded.

**To Reproduce**
1. Go to 'Home Screen'
2. Click on 'some note'
3. Click on the title in the action bar
4. Click on `cancel` or `save` (you don't need to change something)
5. See the error - keyboard is still present (probably okay in edit mode, but no benefit in view mode.)

**Expected behavior**
The keyboard should automatically disappear after finishing the title change.

**Screenshots**
<img src="https://user-images.githubusercontent.com/24355353/121802301-db574b00-cc3b-11eb-885d-65bb4e8bf7d0.jpg" alt="note-title-change" width="200"/> <img src="https://user-images.githubusercontent.com/24355353/121802305-dd210e80-cc3b-11eb-9cf1-95d2019fa6b7.jpg" alt="note-close" width="200"/>

**Smartphone (please complete the following information):**
 - Nextcloud Notes-Version F-Droid or Play Store: 3.4.8
 - Android-Version: 9
 - Device: Huawei P10
 - Keyboard: Microsoft Swift (personal opinion: should also work with Google Keyboard or any other)

**Comment by joshtrichards** [comment]
I'm not seeing this behavior today. Are you still experiencing it?
