### ISSUE TITLE
Text fields in dialogs are collapsed when keyboard is showing (Edit Title & Category)

### ISSUE THREAD

**Issue by thgoebel** [nextcloud/notes-android#1660]
Please use **[GitHub reactions](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/)** 👍 to show that you are affected by the same issue. Please don't comment if you have no relevant information to add!

**Describe the bug**

On small-enough devices the content of the text field in dialogs is collapsed and not fully visible.

I can reproduce this on an OnePlus 5, with a screen size of 139.7 mm / 5.5 in.

You can type text, but it will only be visible when you collapse the keyboard (then the text field expands to normal size).
iirc the Files app also had a similar issue after migrating to Material 3.

**To Reproduce**

1. Open a note
2. Click on the overflow menu
3. Click "Edit title" OR "Category"

**Expected behavior**

Never collapse the text field.

**Screenshots**

<img src=https://user-images.githubusercontent.com/33295590/215613327-47b4c54c-e5fb-44f4-b1a9-9d6ac029c44e.png width=55%>

**Smartphone**
 - Nextcloud Notes-Version (android app): 3.7.1
 - F-Droid or Play Store: F-Droid
 - Android-Version: 13
 - Device: cheeseburger

**Server**
 - Nextcloud version: n/a
 - Nextcloud Notes version (server app): n/a

**Stacktrace**

n/a

**Comment by stefan-niedermann** [comment]
Can you please post the screen size (in inches) and resolution of your device?

**Comment by thgoebel** [comment]
5.5 inches and 1080 x 1920 resolution

**Comment by AlvaroBrey** [comment]
Relevant fix from Files: https://github.com/nextcloud/android/pull/10962/files 

The only way to fix it there was to change the way we were opening the soft keyboard. And yes the delay was also necessary :(

**Comment by cieska** [comment]
Same here 
![Screenshot_20230220-164216](https://user-images.githubusercontent.com/41318524/220162699-66190c66-583c-45af-bd39-8af56de82e4e.jpg)
![Screenshot_20230220-164208](https://user-images.githubusercontent.com/41318524/220162704-0818d72e-0590-49d9-bf69-29ffd48c4428.jpg)
