### ISSUE TITLE
grammar fix / suggestion?

### ISSUE THREAD

**Issue by roliverio** [nextcloud/notes-android#1667]
Hi!, 

inside app/src/main/res/values/strings.xml 

You have a "founder" string, within the translation team we're wondering if you want to keep it this way, or maybe change the wording to "Author", or at least "Founder" (capitalized) 

Give us a quick reply, and do fix the value to ensure proper translation.

**Comment by tobiasKaminsky** [comment]
This is used here:

![2023-02-02-092621](https://user-images.githubusercontent.com/5836855/216270862-dbf7f2b4-ac55-407c-b9ee-e4351dacf7f5.png)

As a non-native speaker, I am not sure if it is (founder) or (Founder).

**Comment by AlvaroBrey** [comment]
@roliverio as Tobias said, this string is used to mark the founder of this app in the credits screen. Perhaps a better wording would be "original author"? I don't think just "author" is the proper word here as it doesn't convey the same meaning,

**Comment by stefan-niedermann** [comment]
Initiator? 🤔

**Comment by AlvaroBrey** [comment]
> Initiator? thinking

That also doesn't sound right to me in English... I guess "creator" would be another possibility but I still think "original author" sounds better

**Comment by roliverio** [comment]
Well guys, thanks for giving this quick comment a peek!, please then update the string on the code so the transifex change comes up to update it.

**Comment by AlvaroBrey** [comment]
@stefan-niedermann @tobiasKaminsky are we okay with "original author"? or do we just leave "founder"?

**Comment by stefan-niedermann** [comment]
I don't have a strong opinion here - fine with all of the suggested :slightly_smiling_face:

**Comment by tobiasKaminsky** [comment]
Original author is most fitting, I think.
