### ISSUE TITLE
Monochrome app icon is missing

### ISSUE THREAD

**Issue by stefan-niedermann** [nextcloud/notes-android#1715]
![Screenshot_20230321-085504_Trebuchet](https://user-images.githubusercontent.com/4741199/226546361-cc74a68a-a272-49ff-a052-352b5ba91753.png)

Probably happened while changing the app icon.

Noticed in 4.0.0 RC1

CC @AlvaroBrey @tobiasKaminsky

**Comment by AlvaroBrey** [comment]
Woops: https://github.com/nextcloud/notes-android/commit/e37bf5f99daf95c5cd93ec7be72112057156406f#diff-4ad5cae7a11ab064a2f2b6e205535c148c66267f95cee8dad3ccdd54e6e17064

Restoring the `<monochrome>` tag should fix it
