### ISSUE TITLE
Option to create notes with .md extension instead of .txt

### ISSUE THREAD

**Issue by adrienneteicher** [nextcloud/notes-android#1728]
The Nextcloud Notes server app allows users to select ".md" as the extension for notes. It would be great to have this functionality in the Android app.

There is a discussion of this feature request here: https://github.com/nextcloud/notes/issues/24
It was eventually implemented. The same solution could be implemented in the Android notes app.

**Comment by stefan-niedermann** [comment]
It is. Choose your account avatar in the top right, select `Manage accounts`.

**Comment by stefan-niedermann** [comment]
It is there because this setting is account related and not app related 😉

**Comment by adrienneteicher** [comment]
Thanks so much! I searched a lot and couldn't find this information anywhere.

**Comment by jpggithub** [comment]
Same here ! ;-) 
Perhaps it could be added to the features of the app?
