### ISSUE TITLE
The app doesn't support themed icons after update 

### ISSUE THREAD

**Issue by goremykin** [nextcloud/notes-android#1733]
Please use **[GitHub reactions](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/)** 👍 to show that you are affected by the same issue. Please don't comment if you have no relevant information to add!

**Describe the bug**
Previously it had a nice themed icon
https://developer.android.com/develop/ui/views/launch/icon_design_adaptive

**To Reproduce**
1. Enable themed icons feature
2. Add the app to the home screen 

**Expected behavior**
The icon is adopted to theme

**Screenshots**
![Screenshot_20230328-225019_DerpLauncher.png](https://user-images.githubusercontent.com/25577658/228363902-8b4e00af-eb4f-4c08-9da2-8edabb675b6c.png)

**Smartphone (please complete the following information):**
 - Nextcloud Notes-Version (android app): 4.0.0 rc1
 - F-Droid or Play Store: F-Droid
 - Android-Version: 13
 - Device: Xiaomi mi 9t

**Server**
 - Nextcloud version: 26.0.0
 - Nextcloud Notes version (server app): 4.7.2

P.S. Thank you very much for this nice app. It is really cool!

**Comment by stefan-niedermann** [comment]
https://github.com/nextcloud/notes-android/issues/1715
