### ISSUE TITLE
Proxy 

### ISSUE THREAD

**Issue by likehopper** [nextcloud/notes-android#1735]
Could the app use the http proxy specified by Android's wifi connection?

**Comment by stefan-niedermann** [comment]
The app uses the Nextcloud files app as a proxy - when the Nextcloud files app uses the system proxy, the Notes app should do it as well - if not, this issue must be opened in the repository of the Nextcloud files app.

**Comment by joshtrichards** [comment]
@likehopper This isn't relevant to the Notes app. I suspect, if anything, you intended to open this for the [Nextcloud Android client](https://github.com/nextcloud/android/).

A cursory search suggests it may not be officially supported - e.g. https://github.com/nextcloud/android/issues/606
