### ISSUE TITLE
Nextcloud Collectives App

### ISSUE THREAD

**Issue by pschopen** [nextcloud/notes-android#1818]
Maybe it would make sense to take the work from Nextcloud Notes and use it for a Nextcloud Collectives App? Editing and storing .MD-Files would be the same and only the folder structure would need any change?

**Comment by stefan-niedermann** [comment]
Please use the 🔍  **search function** before opening new issues.

Closing as duplicate of https://github.com/nextcloud/notes-android/issues/1658

**Comment by pschopen** [comment]
Are there any plans in that regard?
