### ISSUE TITLE
Prevent RCs from being delivered/deployed/built by F-Droid

### ISSUE THREAD

**Issue by rugk** [nextcloud/notes-android#1869]
Please use **[GitHub reactions](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/)** 👍 to show that you are affected by the same issue. Please don't comment if you have no relevant information to add!

**Describe the bug**

https://github.com/nextcloud/notes-android/issues/1833 likely also was so bad because it got delivered to all F-Droid users.

**To Reproduce**
F-Droid currently promotes the rc as stable.

**Expected behavior**

RCs etc. should not be considered stable.

AFAIK some metadata update may be needed.

But this can prevent many issues in the future.

**more**

This could help: https://forum.f-droid.org/t/how-to-mark-releases-as-pre-releases/1246?user=rugk

**Comment by fmikker** [comment]
Hi, Is there any estimate on when 4.1 final is released to f-droid?

**Comment by scollovati** [comment]
Seems to be solved according to this comment https://github.com/nextcloud/notes-android/issues/1876#issuecomment-1717198976
