### ISSUE TITLE
Open specific Notice via Widget starts new Notice

### ISSUE THREAD

**Issue by Bitsauger** [nextcloud/notes-android#2147]
### This issue respects the following points:

- [X] I have read the [FAQ](https://github.com/nextcloud/notes-android/blob/master/FAQ.md)
- [X] I have searched for existing issues
- [X] The issue affects the Notes Android app, neither the [Notes server app](https://github.com/nextcloud/notes/issues/) nor the [Nextcloud Android app](https://github.com/nextcloud/android/issues).

### Describe the bug

Create a a widget on Homescreen for a specific Note.
You can now scroll the specific Note within the Homescreen.
If you click on the Note I'd expect to edit directly this specific Note as it was before.
But it starts to create a new one...

### Expected behavior

Touch on the Widget on the Homescreen opens this Note and does'nt start a new one.

### Notes Android version

4.2.1

### Notes server version

4.9.4

### Nextcloud Android version

3.28.2

### Nextcloud version

Hub7 28.0.4

### Device

Samsung Galaxy S23Plus

### Android Version

14

### App Store

- [X] Google Play Store
- [ ] F-Droid
- [ ] Huawei App Gallery

**Comment by KopfKrieg** [comment]
Same here on a Pixel 6a, Stock OS (Android 14), with Nextcloud Notes installed from F-Droid (v4.2.1)

**Comment by MrDiamond10** [comment]
Same on Nexctloud Notes app v.4.2.1 form F-Droid. Android 14. Nextcloud app v Nextcloud Dev v.20242427
