### ISSUE TITLE
Widget: List of notes doesnt load specific note

### ISSUE THREAD

**Issue by Mnikley** [nextcloud/notes-android#2148]
### This issue respects the following points:

- [X] I have read the [FAQ](https://github.com/nextcloud/notes-android/blob/master/FAQ.md)
- [X] I have searched for existing issues
- [X] The issue affects the Notes Android app, neither the [Notes server app](https://github.com/nextcloud/notes/issues/) nor the [Nextcloud Android app](https://github.com/nextcloud/android/issues).

### Describe the bug

1. Create new widget for list of notes
2. Select any note-folder
3. Try to click on one of the notes --> noting happens
---
Displaying the notes & scrolling through the headings works, adding new notes and viewing existing ones doesnt.
This occurred after upgrading from 4.2.0 to 4.2.1. When upgrading, I got an error initially and the old list of notes widget didnt show any data. Removing this old widget and adding a new one fixed the occurrence of the error, but still doesnt fix the above mentioned bug. Unfortunately I was not able to capture the error.

### Notes Android version

4.2.1

### Notes server version

4.9.4

### Nextcloud Android version

3.28.2

### Nextcloud version

28.0.4

### Device

Google Pixel 7a (GrapheneOS)

### Android Version

14

### App Store

- [ ] Google Play Store
- [ ] F-Droid
- [ ] Huawei App Gallery
- [x] Aurora Store

**Comment by pantherman594** [comment]
This is a known issue which unfortunately does not have a fix yet: https://github.com/nextcloud/notes-android/issues/2091#issuecomment-2067956228
