### ISSUE TITLE
Synchronisation hanging and list widget dead

### ISSUE THREAD

**Issue by Phaet** [nextcloud/notes-android#2160]
### This issue respects the following points:

- [X] I have read the [FAQ](https://github.com/nextcloud/notes-android/blob/master/FAQ.md)
- [X] I have searched for existing issues
- [X] The issue affects the Notes Android app, neither the [Notes server app](https://github.com/nextcloud/notes/issues/) nor the [Nextcloud Android app](https://github.com/nextcloud/android/issues).

## App
1. Swipe down the screen to start sync
2. Spinner spins forever

## List widget
Nothing happens when tapping a note nor the plus nor the widget title

### Expected behavior

After installing the notes app the existing notes are synced. That is the app connects successfully.
But afterwards see above.

### Notes Android version

4.2.1

### Notes server version

4.10.0

### Nextcloud Android version

3.29.0

### Nextcloud version

28.0.4

### Device

Samsung Galaxy S24

### Android Version

14

### App Store

- [X] Google Play Store
- [ ] F-Droid
- [ ] Huawei App Gallery

**Comment by Phaet** [comment]
After update the Notes server version to 4.10.0 sync seems to work. I created and deleted a note and the widget reflects the changes.
But still the widget is dead as described.

**Comment by Phaet** [comment]
Sync seems to work only now and than. Got

App Version: 4.2.1
App Version Code: 40020190
App Flavor: play

Files App Version Code: 30290090 (PROD)

---

OS Version: 6.1.43-android14-11-abS921BXXU1AXCA(S921BXXU1AXCA)
OS API Level: 34
Device: e1s
Manufacturer: samsung
Model (and Product): SM-S921B (e1sxeea)

---

java.lang.Exception: com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was BEGIN_ARRAY at line 1 column 2 path $
 at it.niedermann.owncloud.notes.persistence.NotesServerSyncTask.pushLocalChanges(NotesServerSyncTask.java:174)
 at it.niedermann.owncloud.notes.persistence.NotesServerSyncTask.run(NotesServerSyncTask.java:94)
 at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:487)
 at java.util.concurrent.FutureTask.run(FutureTask.java:264)
 at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
 at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
 at java.lang.Thread.run(Thread.java:1012)

**Comment by stefan-niedermann** [comment]
> I have searched for existing issues

Are you kidding me? Position 3 of the list. First when searching for "Widget".

> JsonSyntaxException

There are various issues, when you search for that term. Read them, check if some of the environment is as yours, and if you find nothing, reopen the issue and write about your environment, server logs, installed app, everything that might help.
