### ISSUE TITLE
Existing notes cannot be edited

### ISSUE THREAD

**Issue by der-domi** [nextcloud/notes-android#2372]
### This issue respects the following points:

- [X] I have read the [FAQ](https://github.com/nextcloud/notes-android/blob/master/FAQ.md)
- [X] I have searched for existing issues
- [X] The issue affects the Notes Android app, neither the [Notes server app](https://github.com/nextcloud/notes/issues/) nor the [Nextcloud Android app](https://github.com/nextcloud/android/issues).

### Describe the bug

*Issue*:
1. Set following settings
   * Notes opening preview: Plain preview
   * Direct Edit: enabled
   * Grid view: disabled
   * Monospace font: disable
   * Font size: Medium
   * Keep screen on: enabled
 2. Open an existing note
 3. Hit the button: Plain edit mode
    * **Result**: Note cannot be edited

*Workaround*:
1. Change following setting:
   * Direct Edit: disabled
 2. Open an existing note
 3. Hit the button: Plain edit mode
    * **Result**: Note can be edited

*Hint*
Issue obsurved also on another device with Lineage-21 and same apps.

### Expected behavior

Notes can be edited also if the setting `Direct Edit` is enabled (which is the default).

### Notes Android version

4.3.1

### Notes server version

4.10.1

### Nextcloud Android version

3.29.1

### Nextcloud version

29.0.6

### Device

Fairphone 5

### Android Version

14

### App Store

- [ ] Google Play Store
- [X] F-Droid
- [ ] Huawei App Gallery

### Stacktrace

not applicable

**Comment by AssassinTee** [comment]
I got the same issue, I can add my stats if you want too.

Workaround:
Go into settings and set "behaviour on opening notices" to "simple edit mode" so you can edit notes directly

![Screenshot_20240918-114323](https://github.com/user-attachments/assets/327c1557-7a20-4345-9bd7-fd1a91fd4a94)

**Comment by stefan-niedermann** [comment]
What do you mean by "Note can not be edited"?

Does it not open?
Does it open but readonly?
Can you edit but changes are not saved?
Is only one specific note affected or all?
Is the note shared from another user?
Are you able editing via the web UI?

Please describe your issue more and / or post screenshots or videos.

**Comment by der-domi** [comment]
Sorry for missing Information. 

I am pushing the edit button but nothing happens. The note still stays in viewing mode.
![Screenshot_20240918-140559_1](https://github.com/user-attachments/assets/aaccd001-789c-4de7-8970-713d557cc08b)

It happens to all notes. All my notes are shared **to** another user.

In can edit the Note:
- with Web UI
- with Nextcloud app
- By applying the workaround above descriped

**Comment by toxpal** [comment]
Same issue here on 2 phones with Android 14. Worked fine in the past...

**Comment by bessw** [comment]
Same issue, startet last monday. I created a new Markdown note using the Android App and added a few lines. Then I locked my phone talked to someone for a minute and when I wanted to continue editing the "Einfacher Bearbeitungsmodus" button didn't work anymore.

Even after restarting the app the button desn't work, no matter which note I try to edit.

**Comment by bessw** [comment]
The issue still persists, is the fix already released?
